all : SerialTransfer

SerialTransfer:
	@echo 
	@echo ============= Build SerialTransfer ===============
	@echo 
	
	make -C 01.SerialTransfer

	@echo 
	@echo =============== Build Complete ===============
	@echo

clean:
	make -C 01.SerialTransfer clean